name: Create env file

on:
  workflow_call:

jobs:
  create-env-file:
    name: Create env file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Create env file
        run: |
          echo "COSMOS_ENDPOINT=${{ secrets.COSMOS_ENDPOINT }}" >> .env
          echo "COSMOS_KEY=${{ secrets.COSMOS_KEY }}" >> .env
  
