name: CI - Commit Linter

on:
  workflow_call:
    inputs:
      node_version:
        description: 'Node.js version to use'
        required: false
        default: '14'
        type: string

jobs:

  initialize_environment:
    uses: ./.github/workflows/initialize_linux_env.yml
    with:
      distros: '["ubuntu-22.04"]'
      commands: '["sudo apt update", "sudo apt install -y sudo", "sudo apt install -y git curl", "sudo curl -fsSL https://deb.nodesource.com/setup_${{ inputs.node_version }}.x | sudo -E bash -", "sudo DEBIAN_FRONTEND=noninteractive apt install -y nodejs"]'
      version_commands: '["git --version", "node --version", "npm --version", "npx commitlint --version"]'

  commitlint:
    needs: initialize_environment
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install commitlint
        run: |
          npm install conventional-changelog-conventionalcommits
          npm install commitlint@latest

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: npx commitlint --last --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
